name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - master
      - develop

env:
  # Docker 이미지 관련 설정
  DOCKER_IMAGE: ghcr.io/${{ github.repository_owner }}/predix-agent
  VERSION: ${{ github.sha }}
  CONTAINER_NAME: predix-agent

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ github.ref == 'refs/heads/master' && 'latest' || 'develop' }}
          no-cache: true

  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ${{ github.ref == 'refs/heads/master' && 'prod' || 'dev' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup environment file
        run: |
          if [ "${GITHUB_REF}" = "refs/heads/master" ]; then
            echo "${{ secrets['ENV_PRD'] }}" > .env
          else
            echo "${{ secrets['ENV_DEV'] }}" > .env
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Stop and remove existing container
        run: |
          docker stop ${{ env.CONTAINER_NAME }} || true
          docker rm ${{ env.CONTAINER_NAME }} || true

      - name: Remove existing Docker image
        run: |
          docker rmi ${{ env.DOCKER_IMAGE }}:${{ github.ref == 'refs/heads/master' && 'latest' || 'develop' }} || true

      - name: Run Docker container
        run: |
          docker run -d \
            -p 5021:80 \
            --name ${{ env.CONTAINER_NAME }} \
            --restart always \
            --env-file .env \
            -v /home/ec2-user/predix-agent/logs:/code/logs \
            ${{ env.DOCKER_IMAGE }}:${{ github.ref == 'refs/heads/master' && 'latest' || 'develop' }}
